#!/bin/bash

echo "Backing up system .vimrc and .bashrc into setup folder..."

# Check if vimrc is updated
echo -e "\nDiffering vimrc..."
if diff ../.vimrc vimrc >/dev/null ; then
    echo "no changes in vimrc, no backup needed"
else
    # Ask to backup
    echo "There are new changes to .vimrc"
    read -p "Do you want to backup vimrc? " yn
    case $yn in
        [Yy]* )
            echo -e "\nbacking up vimrc...";
            echo "copying vimrc";
            cp ../.vimrc vimrc;
            break;;
        * )
            echo -e "\nNot backing up .vimrc.";;
esac
fi

# Check if bashrc is updated
echo -e "\nDiffering bashrc..."
if diff ../.bashrc bashrc >/dev/null ; then
    echo "no changes in bashrc, no backup needed"
else
    echo "There are new changes to .bashrc"
    read -p "Do you want to backup bashrc? " yn
    case $yn in
        [Yy]* )
            echo -e "\nbacking up bashrc...";
            echo "copying bashrc";
            cp ../.bashrc bashrc;
            break;;
        * )
            echo -e "\nNot backup up .bashrc.";;
esac
fi

echo -e "\nending script."
