#!/bin/bash

BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc

vim -u ~/.vimrc.old +PlugInstall +qall

# tmux
mv -v ~/.tmux.conf ~/.tmux.conf.old 2> /dev/null
ln -sf $BASE/tmux.conf ~/.tmux.conf
