#!/bin/bash

BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# Git
git config --global user.name "Jeffrey Wu"
git config --global user.email "jeffreywu1996@gmail.com"

# vimrc
[ -f ~/.vimrc ] && mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc

vim +PlugInstall +qall

# tmux
mv -v ~/.tmux.conf ~/.tmux.conf.old 2> /dev/null
ln -sf $BASE/tmux.conf ~/.tmux.conf

# Install node (needed by coc)
if ! which node > /dev/null
then
  curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  sudo apt-get install -y nodejs
fi

# Install fg (used by fzf)
if ! which fd > /dev/null
then
  sudo apt-get install -y fd-find
fi
